global_seed: 25126
global_batch_size: 2
epochs: 1000
results_dir: "results"
lr: 0.0001
weight_decay: 1e-5
autocast: False
model: "ViT3D-S/8"
num_workers: 4
ckpt_every: 5000

num_frames: 92  #max 120

img_size: 196

#load from pretrain checkpoint
init_from_pretrain_ckpt: False
pretrain_ckpt_path: ""

use_compiler: False

wandb: False
oversampled: True

use_clip_norm: False
start_clip_epoch: 100

accumulation_steps: 1

use_focal_loss: True

log_every: 10

train_npy_dir: '/root/code/MRIclass/datasets/train/'  
excel_path: '/root/code/MRIclass/datasets/SLN_WCH_final version_new.xlsx'   

sample_batch_size: 1
sample_global_seed: 25126
sample_ckpt_path: "/root/code/MRIclass/results/000-ViT3D-S-8/checkpoints/0035000.pt"
use_ema: False
test_npy_dir: '/root/code/MRIclass/datasets/test/'  
